litellm_settings:
  drop_params: true
  set_verbose: true

model_list:
  - model_name: mistral-7b
    litellm_params:
      model: ollama/mingli512/mistral-7b-openorca-Q2_K
      api_base: http://127.0.0.1:11434
      headers: {
        "HTTP-Referer": "litellm.ai",  
        "X-Title": "LiteLLM Server"
      }
- model_name: phi
    litellm_params:
      model: ollama/phi
      api_base: http://127.0.0.1:11434
      headers: {
        "HTTP-Referer": "litellm.ai",
        "X-Title": "LiteLLM Server"
      }

